TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += ngpspsu.db

#protocol files
DATA += ngpspsu.proto

#=======================================
include $(TOP)/configure/RULES
