TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += ngpspsu.db
DB += status_hex.db
DB += voltage.db
DB += current.db

#protocol files
DATA += ngpspsu.proto

#=======================================
include $(TOP)/configure/RULES
